### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by amouly** [snakepit13/contactlist#8]
Definitely much better than before. Some minor details:

You are using Holo Design for old Android devices "android:Theme.Holo.Light.DarkActionBar".

This can be avoid by using the latest versions of support library (v7 and Design), which includes Toolbar and some Material design widgets. This allow you to provide Material design for each version of Android starting from 2.1.

Remember that Interfaces in Java has always public methods. You don't need to declare each method as public explicit.

If you see each 'Parcelable' that you implemented, you can see a linter error which says that the "creator" is missing. This need to be implemented in each case.

**Comment by amouly** [comment]
As a minor improvement, take a look at this library: http://jakewharton.github.io/butterknife/

It's for View Injection, very useful and pretty standard on any Android project.

**Comment by figui** [comment]
OK, i will change these minor changes and then close the issues to notify you

**Comment by amouly** [comment]
:+1:

**Comment by figui** [comment]
Done!!

**Comment by amouly** [comment]
:+1:
